version: '3.7'

services:
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'signing_redis_data:/bitnami/redis/data'

volumes:
  signing_redis_data: